---
- name: installing packages
  hosts: all
  tasks:
  - name: To install httpd package
    yum:
      name: httpd
      state: present
    notify: start the service  
  
  handlers:
  - name: To start the service
    service:
      name: httpd
      state: started    