---
- name: installing packages
  hosts: all
  tasks:
  - name: To install httpd package
    yum:
      name: httpd
      state: present

  - name: To start the service
    service:
      name: httpd
      state: started    