---

- name: To create the users using the variables
  hosts: all
  become: true
# vars:
#- user_name: rocky
  vars_files:
  - /home/ansadmin/var.yaml
  tasks:
  - name: create a user {{ user_name }}
    user:
    - name: "{{ user_name }}"
       
  - name: to create a directory for {{ user_name }}
    file:
    - path: /opt/user_name
      state: directory
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: '0755'       